---
- name: playbook new
  hosts: webservers
  vars:
   a: "This is First Playbook"
   b: "This is Second Playbook"
  tasks:
   - name: task-1
     debug:
      msg: "{{a}}"
   - name: task-2
     debug:
      msg: "{{b}}"
...

